# How to visualize a vector field

This notebook demonstrates some features of `feedWebGL2` for visualizing vector fields.

A vector field is characterized by 3 dense arrays of floating point values representing
the (x, y, z) components of direction vectors at each (i, j, k) index of the arrays.
In real applications these arrays would be derived from remote sensing of some sort of
scientific simulation.

In this demonstration, for simplicity, we invent some arrays with no motivation physical intuition
behind them

In [1]:
import numpy as np

In [2]:
array_size = 300
x_values = np.linspace(0, 2.0, array_size)
y_values = np.linspace(0, 2.0, array_size)
z_values = np.linspace(0, 2.0, array_size)

In [3]:
# make X Y and Z matrices for calculations
# (adapted from https://numpy.org/doc/stable/reference/generated/numpy.meshgrid.html)
X, Y, Z = np.meshgrid(x_values, y_values, z_values) 

In [4]:
# create X Y and Z vector component arrays using arbitrary calculations
x_component = np.sin(Y + Z)
y_component = np.cos(X + Z)
z_component = np.sin(X + Y + Z)

In [5]:
# Visualize the vector field.
from feedWebGL2 import vector_field_3d
vector_field_3d.widen_notebook()

In [6]:
# For generating isosurfaces, subsample the arrays with a stride of 6
viewer = vector_field_3d.VectorFieldViewer(x_component, y_component, z_component, subsample=6)

In [7]:
# generate a widget illustrating the field, using 100 streamlines started at random start points.
viewer.displayWidget(100)

# Explanation:

In the visualization the solid surfaces represent the iso-surfaces of the magnitude of the
vector field at each index.

The animated streamlines indicate the direction of flow for the vector field.

# Specifying start points

To specify starting points for the streamlines, provide a list of points in place of the number of points.

In [12]:
starting_points = []
for i in range(100):
    x = 150
    z = 150 * (1 + np.sin(i))
    y = 150 * (1 + np.cos(i))
    # NOTE (z, y, x) not xyz
    point = np.array([z,y,x])
    starting_points.append((point))
    
viewer.displayWidget(zyx_start_points=starting_points, max_number_of_points=150)

In [9]:
starting_points

[array([150., 152., 150.]),
 array([150.        , 151.54030231, 276.22064772]),
 array([150.        , 150.58385316, 286.39461402]),
 array([150.        , 150.0100075 , 171.16800121]),
 array([150.        , 150.34635638,  36.4796257 ]),
 array([150.        , 151.28366219,   6.1613588 ]),
 array([150.        , 151.96017029, 108.08767527]),
 array([150.        , 151.75390225, 248.54798981]),
 array([150.        , 150.85449997, 298.40373699]),
 array([150.        , 150.08886974, 211.81777279]),
 array([150.        , 150.16092847,  68.39683337]),
 array([1.50000000e+02, 1.51004426e+02, 1.46901739e-03]),
 array([150.        , 151.84385396,  69.5140623 ]),
 array([150.        , 151.90744678, 213.02505552]),
 array([150.        , 151.13673722, 298.59110335]),
 array([150.        , 150.24031209, 247.54317602]),
 array([150.        , 150.04234052, 106.8145025 ]),
 array([150.        , 150.72483666,   5.79037622]),
 array([150.        , 151.66031671,  37.35191298]),
 array([150.        , 151.9887